export const EXTRA_MOCK_JOBS = [
  {
    id: 'job-5',
    title: 'Twitch Stream Sponsorship - Apex Legends',
    organization: { brand_name: 'Logitech G', bio: 'Play to win.', website: 'https://logitechg.com', reputation: 4.9, logo_url: 'https://www.google.com/s2/favicons?domain=logitechg.com&sz=128' },
    description: 'We are looking for Twitch streamers to showcase our new G Pro Wireless mouse during a 2-hour Apex Legends stream.',
    target_platform: 'other',
    post_type: 'video',
    payout_type: 'full',
    total_budget: 2000,
    status: 'open',
    required_elements: { hashtags: ['LogitechG', 'PlayToWin'], mentions: ['@LogitechG'] },
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    deadline: new Date(Date.now() + 86400000 * 5).toISOString(),
  },
  {
    id: 'job-6',
    title: 'Instagram Carousel - Summer Wardrobe',
    organization: { brand_name: 'Zara', bio: 'Latest trends in fashion.', website: 'https://zara.com', reputation: 4.6, logo_url: 'https://www.google.com/s2/favicons?domain=zara.com&sz=128' },
    description: 'Create a 5-slide carousel post featuring our new summer collection. Clothing will be provided.',
    target_platform: 'instagram',
    post_type: 'image',
    payout_type: 'milestone',
    total_budget: 800,
    status: 'open',
    required_elements: { hashtags: ['ZaraSummer', 'OOTD'], mentions: ['@Zara'] },
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    deadline: new Date(Date.now() + 86400000 * 7).toISOString(),
  },
  {
    id: 'job-7',
    title: 'YouTube Tutorial - Intro to Web3',
    organization: { brand_name: 'Coinbase', bio: 'The easiest place to buy and sell cryptocurrency.', website: 'https://coinbase.com', reputation: 4.8, logo_url: 'https://www.google.com/s2/favicons?domain=coinbase.com&sz=128' },
    description: 'Create a 15-minute beginner-friendly tutorial on how to set up a Web3 wallet and make your first transaction.',
    target_platform: 'youtube',
    post_type: 'video',
    payout_type: 'full',
    total_budget: 4500,
    status: 'open',
    required_elements: { hashtags: ['Web3', 'Crypto'], mentions: ['@Coinbase'] },
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    deadline: new Date(Date.now() + 86400000 * 14).toISOString(),
  },
  {
    id: 'job-8',
    title: 'TikTok Recipe - Healthy Snacks',
    organization: { brand_name: 'Whole Foods', bio: 'Highest quality natural and organic products.', website: 'https://wholefoodsmarket.com', reputation: 4.7, logo_url: 'https://www.google.com/s2/favicons?domain=wholefoodsmarket.com&sz=128' },
    description: 'Share a quick, under 60-second healthy snack recipe using ingredients exclusively from Whole Foods.',
    target_platform: 'tiktok',
    post_type: 'video',
    payout_type: 'full',
    total_budget: 900,
    status: 'open',
    required_elements: { hashtags: ['HealthySnacks', 'WholeFoods'], mentions: ['@WholeFoods'] },
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
    deadline: new Date(Date.now() + 86400000 * 3).toISOString(),
  },
  {
    id: 'job-9',
    title: 'Twitter Giveaway Campaign',
    organization: { brand_name: 'Ledger', bio: 'Secure your crypto.', website: 'https://ledger.com', reputation: 4.9, logo_url: 'https://www.google.com/s2/favicons?domain=ledger.com&sz=128' },
    description: 'Host a giveaway for a Ledger Nano X on your Twitter account. We will provide the prize and the copy.',
    target_platform: 'twitter',
    post_type: 'content_writing',
    payout_type: 'full',
    total_budget: 600,
    status: 'open',
    required_elements: { hashtags: ['CryptoSecurity', 'Giveaway'], mentions: ['@Ledger'] },
    created_at: new Date(Date.now() - 3600000 * 48).toISOString(),
    deadline: new Date(Date.now() + 86400000 * 2).toISOString(),
  },
  {
    id: 'job-10',
    title: 'Instagram Story Takeover',
    organization: { brand_name: 'Spotify', bio: 'Listening is everything.', website: 'https://spotify.com', reputation: 4.8, logo_url: 'https://www.google.com/s2/favicons?domain=spotify.com&sz=128' },
    description: 'Take over our official Instagram account for a day and share your favorite summer playlists and music discovery tips.',
    target_platform: 'instagram',
    post_type: 'video',
    payout_type: 'milestone',
    total_budget: 2500,
    status: 'open',
    required_elements: { hashtags: ['SpotifyTakeover', 'SummerHits'], mentions: ['@Spotify'] },
    created_at: new Date(Date.now() - 3600000 * 72).toISOString(),
    deadline: new Date(Date.now() + 86400000 * 10).toISOString(),
  },
  {
    id: 'job-11',
    title: 'YouTube Gameplay Walkthrough',
    organization: { brand_name: 'Epic Games', bio: 'Creators of Fortnite and Unreal Engine.', website: 'https://epicgames.com', reputation: 4.5, logo_url: 'https://www.google.com/s2/favicons?domain=epicgames.com&sz=128' },
    description: 'Produce a 20-minute gameplay video for the new season of Fortnite, highlighting the new map changes.',
    target_platform: 'youtube',
    post_type: 'video',
    payout_type: 'full',
    total_budget: 3500,
    status: 'open',
    required_elements: { hashtags: ['Fortnite', 'EpicGames'], mentions: ['@EpicGames'] },
    created_at: new Date(Date.now() - 3600000 * 10).toISOString(),
    deadline: new Date(Date.now() + 86400000 * 8).toISOString(),
  },
  {
    id: 'job-12',
    title: 'TikTok Fitness Transformation',
    organization: { brand_name: 'Gymshark', bio: 'Be a visionary.', website: 'https://gymshark.com', reputation: 4.7, logo_url: 'https://www.google.com/s2/favicons?domain=gymshark.com&sz=128' },
    description: 'Create a TikTok showing a 30-day fitness transformation or your daily routine wearing our new seamless collection.',
    target_platform: 'tiktok',
    post_type: 'video',
    payout_type: 'milestone',
    total_budget: 1500,
    status: 'open',
    required_elements: { hashtags: ['Gymshark', 'FitnessJourney'], mentions: ['@Gymshark'] },
    created_at: new Date(Date.now() - 3600000 * 30).toISOString(),
    deadline: new Date(Date.now() + 86400000 * 20).toISOString(),
  },
  {
    id: 'job-13',
    title: 'Twitter Space Co-Host',
    organization: { brand_name: 'Binance', bio: 'Exchange the world.', website: 'https://binance.com', reputation: 4.8, logo_url: 'https://www.google.com/s2/favicons?domain=binance.com&sz=128' },
    description: 'Co-host an official Binance Twitter Space discussing the future of DeFi and Web3 payments.',
    target_platform: 'twitter',
    post_type: 'other',
    payout_type: 'full',
    total_budget: 1800,
    status: 'open',
    required_elements: { hashtags: ['BinanceSpace', 'DeFi'], mentions: ['@Binance'] },
    created_at: new Date(Date.now() - 3600000 * 15).toISOString(),
    deadline: new Date(Date.now() + 86400000 * 5).toISOString(),
  },
  {
    id: 'job-14',
    title: 'Instagram Product Photography',
    organization: { brand_name: 'Apple', bio: 'Think different.', website: 'https://apple.com', reputation: 5.0, logo_url: 'https://www.google.com/s2/favicons?domain=apple.com&sz=128' },
    description: 'Capture high-quality, aesthetic lifestyle shots of the new AirPods Max for your Instagram feed.',
    target_platform: 'instagram',
    post_type: 'image',
    payout_type: 'full',
    total_budget: 4000,
    status: 'open',
    required_elements: { hashtags: ['ShotOniPhone', 'AirPodsMax'], mentions: ['@Apple'] },
    created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    deadline: new Date(Date.now() + 86400000 * 12).toISOString(),
  }
];
